# ~/.config/foot/foot.ini

term=xterm-256color
font=Fira Mono:size=16
pad=4x4

[colors-dark]
background=0d0e1c
foreground=989898

# Normal colors
regular0=000000  # black
regular1=ff5f59  # red
regular2=44bc44  # green
regular3=d0bc00  # yellow
regular4=2fafff  # blue
regular5=feacd0  # magenta
regular6=00d3d0  # cyan
regular7=989898  # white

# Bright colors
bright0=000000   # bright black
bright1=ff6b55   # bright red
bright2=70b900   # bright green
bright3=fec43f   # bright yellow
bright4=79a8ff   # bright blue
bright5=f78fe7   # bright magenta
bright6=4ae2f0   # bright cyan
bright7=ffffff   # bright white
